[package]
name = "assembler"
version = "0.1.0"
authors = ["Brent Hamilton <hamilton.bh9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
stringsort = "2.0.0"
